server:
  port: 8021

spring:
  application:
    name: service2

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    disable-delta: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
